xinput set-prop 1 libinput\ Accel\ Profile\ Enabled 0, 0 &
xinput set-prop 2 libinput\ Accel\ Profile\ Enabled 0, 0 &
xinput set-prop 3 libinput\ Accel\ Profile\ Enabled 0, 0 &
xinput set-prop 4 libinput\ Accel\ Profile\ Enabled 0, 0 &
xinput set-prop 5 libinput\ Accel\ Profile\ Enabled 0, 0 &
xinput set-prop 6 libinput\ Accel\ Profile\ Enabled 0, 0 &
xinput set-prop 7 libinput\ Accel\ Profile\ Enabled 0, 0 &
xinput set-prop 8 libinput\ Accel\ Profile\ Enabled 0, 0 &
xinput set-prop 9 libinput\ Accel\ Profile\ Enabled 0, 0 &
xinput set-prop 10 libinput\ Accel\ Profile\ Enabled 0, 0 &
xinput set-prop 11 libinput\ Accel\ Profile\ Enabled 0, 0 &
xinput set-prop 12 libinput\ Accel\ Profile\ Enabled 0, 0 &
xinput set-prop 13 libinput\ Accel\ Profile\ Enabled 0, 0 &
xinput set-prop 14 libinput\ Accel\ Profile\ Enabled 0, 0 &
xinput set-prop 15 libinput\ Accel\ Profile\ Enabled 0, 0 &
xinput set-prop 16 libinput\ Accel\ Profile\ Enabled 0, 0 &
